#!/bin/bash

main() {
    local query
    local path
    while true; do
        if query=$(omen -cmd 'xfs-search "%s"' -prompt ' <xfs-search> '); then
            if path=$(xfs-search "$query" --no-pretty | fzf); then
                exec setsid xdg-open "$path"
                exit
            fi
            continue
        fi
        exit
    done
}

case "$1" in
    -) main ;;
    *) st -t 'slouch' -a -g "80x20+570+300" -e "$0" - ;;
esac
