#!/usr/bin/env bash
level=$(pmset -g batt | grep -o '[0-9]*%' | tr -d %)
color=''

if [[ $level -ge 75 ]]; then
    color='#[fg=green]'
elif [[ $level -ge 25 ]] && [[ $level -lt 75 ]]; then
    color='#[fg=yellow]'
else
    color='#[fg=red]'
fi

line=$(spark 0 "${level}" 100)

echo "${color}[${level}%] ${line:1:1}"
