#!/usr/bin/env bash
if [[ -z "$TMUX" ]] ;then
    # recycle tmux sessions here
    ID=$( tmux ls | grep -vm1 '(attached)$' | cut -d: -f1 ) # get the id of a deattached session
    if [[ -z "$ID" ]]; then # if not available create a new one
        exec tmux new
    else
        exec tmux attach-session -t "$ID"
    fi
else
    exec tmux new
fi
