#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Usage:
    dice [--fancy] [--stats] [--times=T]
    dice (-h | --help)

Options:
    --fancy        Fancy output.
    --times=T      How many times to roll the die. [default: 1]
    --help -h      Show this screen.
"""

from __future__ import print_function, division
import docopt
from random import choice


MAPPING = {
    1: '⚀',
    2: '⚁',
    3: '⚂',
    4: '⚃',
    5: '⚄',
    6: '⚅',
}


def main():
    options = docopt.docopt(__doc__)
    TIMES = int(options['--times'])
    FANCY = options['--fancy']

    for _ in range(TIMES):
        c = choice([1,2,3,4,5,6])
        if FANCY:
            print(MAPPING[c], c)
            continue
        print(c)


if __name__ == '__main__':
    main()
