#!/bin/bash

get_bat_level() {
    BATC=/sys/class/power_supply/BAT0/capacity
    cat $BATC
}

prev_bat='100'
proc_bat_info() {
    if [ "$1" -lt 21 ] && [ "$1" != "$2" ]; then
        notify-send "battery: $1%" -a "bat" -u critical
    fi
}

hydra-head | while read -r event; do
    case "$event" in
        nmcli:connected)    notify-send 'wifi' "connected to $(iwgetid -r)" ;;
        nmcli:disconnected) notify-send 'wifi' 'disconnected' ;;
        nmcli:unavailable)  notify-send 'wifi' 'unavailable' ;;
        battery)
            bat_level=$(get_bat_level)
            proc_bat_info "$bat_level" "$prev_bat"
            prev_bat=$bat_level
            ;;
    esac
done
