#!/bin/bash
GEOMETRY="80x20+570+300"

_st_fzf() {
    # shellcheck disable=2068
    fzf +m --tiebreak=length,end --layout=reverse \
        --color=prompt:7,pointer:7,spinner:2,info:8,hl:2,hl+:2,marker:0 \
        --margin=1,2 --prompt='∴ ' $@
}

_st_run() {
    st -t 'st-launch' -a -g $GEOMETRY -e "$0" "$1" &
}

case "$1" in
    # for some weird reason we need to sleep when we run pdetach
    # to prevent it from exiting prematurely
    _run)
        f=$(compgen -c | sort | grep -v '[:!.{}]\|\[\[\|]]\|\[' | _st_fzf)
        # shellcheck disable=2181
        [ $? = 0 ] && pdetach "$f" && sleep 0.25
        ;;
    _filter)
        cd ~
        f=$(_st_fzf)
        # shellcheck disable=2181
        [ $? = 0 ] && pdetach xdg-open "$f" && sleep 0.25
        ;;
    _window)
        window_ids=$(xprop -root | grep '^_NET_CLIENT_LIST(WINDOW)' | cut -d ' ' -f5-)
        IFS=', ' read -ra IDS <<< "$window_ids"
        choice=$(
            for wid in "${IDS[@]}"; do
                name=$(xwininfo -id "$wid" -wm | grep '^xwininfo:'  | cut -d ' ' -f 5-)
                name="${name:1:-1}"
                [[ $name != 'st-launch' ]] && echo -e "$wid\t$name"
            done | _st_fzf --with-nth 2..
        )
        # shellcheck disable=2181
        [ $? = 0 ] && herbstclient jumpto "$(echo "$choice" | cut -d ' ' -f1)"
        ;;
    run)    _st_run _run    ;;
    filter) _st_run _filter ;;
    window) _st_run _window ;;
    *)      echo 'usage: st-launch run'
            echo '       st-launch filter'
            echo '       st-launch window'
esac
