#!/bin/bash
GEOMETRY="80x20+570+300"

__st_fzf() {
    # shellcheck disable=2068
    fzf +m --layout=reverse --margin=1,2 --prompt='∴ ' -d$'\t' \
        --color=prompt:7,pointer:7,spinner:2,info:8,hl:2,hl+:2,marker:0 $@
}

__st_pdetach() {
    # shellcheck disable=2068
    nohup $@ > /dev/null 2> /dev/null &
    sleep 0.1 # don't question this hack
}

__st_run() {
    st -t 'st-launch' -a -g $GEOMETRY -e "$0" "$1" &
}

__st_window_ids() {
    ids=$(xprop -root | grep '^_NET_CLIENT_LIST(WINDOW)' | cut -d ' ' -f5-)
    IFS=', ' read -ra IDS <<< "$ids"
    for wid in "${IDS[@]}"; do
        name=$(xwininfo -id "$wid" -wm | grep '^xwininfo:' | cut -d ' ' -f 5-)
        name="${name:1:-1}"
        [[ $name != 'st-launch' ]] && echo -e "$wid\t$name"
    done
}

__st_freedesktop_entries() {
    sum=$(ls /usr/share/applications/*.desktop | sort | sha1sum | cut -d ' ' -f1)
    tmp="/tmp/st-launch.drun.$sum"
    if [ -e "$tmp" ]; then
        cat "$tmp" && exit
    fi
    echo '' > "$tmp"
    for file in /usr/share/applications/*.desktop; do
        name=''
        path=''
        term=''
        exec=''
        hide=''
        while IFS= read -r line; do
            case "$line" in
                Name=*) [[ $name = '' ]] && name=$(echo "$line" | cut -d '=' -f2-) ;;
                Path=*) [[ $path = '' ]] && path=$(echo "$line" | cut -d '=' -f2-) ;;
                Exec=*) [[ $exec = '' ]] && exec=$(echo "$line" | cut -d '=' -f2- | grep -v '%[UuFf]') ;;
                Terminal=true) term='y' ;;
                Type=Link)              ;&
                Type=Directory)         ;&
                NoDisplay=true)         ;&
                NotShowIn=*)   hide='y' ;;
            esac
        done < "$file"
        if [[ $hide = '' ]] && [[ $name != '' ]] && [[ $exec != '' ]]; then
            entry="$name\t$term\t$exec\t$path"
            echo -e $entry >> "$tmp"
            echo -e $entry
        fi
    done
}

case "$1" in
    _drun)
        choice=$(__st_freedesktop_entries | __st_fzf --with-nth=1)
        # shellcheck disable=2181
        if [ $? = 0 ]; then
            term=$(echo "$choice" | cut -d$'\t' -f2)
            exec=$(echo "$choice" | cut -d$'\t' -f3)
            path=$(echo "$choice" | cut -d$'\t' -f4)
            [[ $path != '' ]] && (cd "$path" || exit)
            if [[ $term = 'y' ]]; then
                __st_pdetach st -e "$exec"
            else
                __st_pdetach "$exec"
            fi
        fi
        ;;
    _run)
        choice=$(compgen -c | grep -v '[:!.{}]\|\[\[\|]]\|\[\|__st' | __st_fzf)
        # shellcheck disable=2181
        [ $? = 0 ] && __st_pdetach "$choice"
        ;;
    _filter)
        choice=$(cd ~ && __st_fzf)
        # shellcheck disable=2181
        [ $? = 0 ] && __st_pdetach xdg-open "$choice"
        ;;
    _window)
        choice=$(__st_window_ids | __st_fzf --with-nth=2..)
        # shellcheck disable=2181
        if [ $? = 0 ]; then
            wid=$(echo "$choice" | cut -d$'\t' -f1)
            herbstclient jumpto "$wid"
            herbstclient raise "$wid"
        fi
        ;;
    run)    __st_run _run    ;;
    drun)   __st_run _drun   ;;
    filter) __st_run _filter ;;
    window) __st_run _window ;;
    *)      echo 'usage: st-launch run'
            echo 'usage: st-launch drun'
            echo '       st-launch filter'
            echo '       st-launch window'
esac
