#!/bin/bash
buffer='tpc'
header='ctrl-y=yank, ctrl-o=open, return=subst'
if choice=$(
    tmux capture-pane -pJ \
        | rg -ow '[^\s]{6,}' - \
        | sort -u \
        | fzf-tmux -- --expect='ctrl-y,ctrl-o' --header="$header" --layout=reverse); then
    # ctrl-y = yank
    # ctrl-o = open
    # return = insert
    body=$(echo "$choice" | tail -n 1 | tr -d "\n")
    case "$(echo "$choice" | head -n 1)" in
        ctrl-o) xdg-open "$body" ;;
        ctrl-y)
            echo -n "$body" | xsel -ib
            tmux set-buffer -- "$body"
            ;;
        *)
            tmux set-buffer -b "$buffer" "$body"
            tmux paste-buffer -b "$buffer" -t "$TMUX_PANE"
            ;;
    esac
fi
