#!/bin/bash
#   unp
#   ~~~
#
#   Helper script for unpacking archives of any kind.
#   It detects the archive by file extension.
#

if [ x == x"$1" ]; then
  echo 'usage: unp [filenames]'
else
  for fn in "$@"; do
    if [ -f "$fn" ]; then
      case "$fn" in
        *.tar.gz)                tar xvzf "$fn" ;;
        *.tgz)                   tar xvzf "$fn" ;;
        *.tar.bz2)               tar xvjf "$fn" ;;
        *.gz)                    gunzip "$fn" ;;
        *.bz2)                   bunzip2 "$fn" ;;
        *.tar)                   tar xvf "$fn" ;;
        *.zip|*.egg|*.jar|*.whl) unzip "$fn" ;;
        *.rar)                   unrar e "$fn" ;;
        *.7z)                    7z x "$fn" ;;
        *) echo "error: '$fn' is an unknown archive" ;;
      esac
    else
      echo "error: '$fn' is not a valid archive"
    fi
  done
fi
