#!/bin/sh

info=`/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport -I | egrep "state|lastTxRate" | cut -d: -f2 | tr "\\n" ";" | sed 's/^[ ]//g'`

if [ "$info" == "" ]; then
    printf '#[fg=red][!]'
    exit
else
    state=`echo ${info} | cut -d";" -f1-1 | cut -d" " -f2-`
    bandwidth=`echo $info | cut -d";" -f2-2 | cut -d" " -f2-`
    if [ "$state" != 'running' ]; then
        printf '#[fg=red][!]'
    else
        printf "#[fg=green]${bandwidth} mbps"
    fi
fi
