#!/usr/local/bin/bash

usage='
wifi: usage:
    wifi on        turns on wifi
    wifi off       turns off wifi
    wifi cycle     turns on then turns off wifi
'

case $1 in
    on)
        networksetup -setairportpower en0 on
        ;;
    off)
        networksetup -setairportpower en0 off
        ;;
    cycle)
        networksetup -setairportpower en0 off
        networksetup -setairportpower en0 on
        ;;
    -h)
        echo "${usage}" ;;
    *)
        echo "${usage}" ;;
esac
