#!/bin/bash

hc() {
    herbstclient "$@"
}

hc emit_hook reload

# remove all existing keybindings
hc keyunbind --all

# keybindings
Mod=Super # Use the super key as the main modifier

hc keybind $Mod-Control-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-Shift-c close
hc keybind $Mod-Return  spawn st -e choose_tmux_session
hc keybind $Mod-Shift-Return  spawn st
hc keybind $Mod-space   spawn slouch run
hc keybind $Mod-w       spawn slouch window
hc keybind $Mod-e       spawn slouch filter
hc keybind $Mod-Shift-space   spawn slouch drun
hc keybind $Mod-Shift-p       spawn ~/.config/herbstluftwm/open-latest-scrot.sh
hc keybind $Mod-x       spawn xkill
# hc keybind $Mod-i       spawn ~/.config/herbstluftwm/info.sh

# locking
hc keybind $Mod-Shift-l spawn i3lock -fe -ti ~/Downloads/iu-yellow.png

# basic movement
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Up    focus up
hc keybind $Mod-Down  focus down
hc keybind $Mod-Right focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right

# splitting frames
# create an empty frame at the specified direction
bindsplit() {
    hc keybind "$Mod-$1" and \
        . compare tags.focus.floating = false \
        . split "$2" 0.5
}

bindsplit u bottom
bindsplit o right
bindsplit Shift-u top
bindsplit Shift-o left

# resizing frames
resizestep=0.05
hc keybind $Mod-Control-Left  resize left  +$resizestep
hc keybind $Mod-Control-Down  resize down  +$resizestep
hc keybind $Mod-Control-Up    resize up    +$resizestep
hc keybind $Mod-Control-Right resize right +$resizestep

# tags
tag_names=( {1..9} )
tag_keys=( {1..9} 0 )

hc rename default "${tag_names[0]}" || true
for i in "${!tag_names[@]}" ; do
    hc add "${tag_names[$i]}"
    key="${tag_keys[$i]}"
    if ! [ -z "$key" ] ; then
        hc keybind "$Mod-$key"       use_index "$i" #chain , use_index "$i"  , spawn ~/.config/herbstluftwm/tags.sh
        hc keybind "$Mod-Shift-$key" move_index "$i" #chain , move_index "$i" , spawn ~/.config/herbstluftwm/tags.sh
    fi
done

# cycle through tags
# hc keybind $Mod-period use_index +1 --skip-visible
# hc keybind $Mod-comma  use_index -1 --skip-visible

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-c spawn ~/.config/herbstluftwm/float-center.sh
hc keybind $Mod-m spawn ~/.config/herbstluftwm/float-maximise.sh

# ibus
# Really hacky: just intercept the keypress for input method
# switching, and switch it manually
hc keybind Alt-grave spawn ibus-switch

# toggle layout
hc keybind $Mod-t cycle_layout +1 vertical max grid

# proprietary bindings
# if we are in a gnome-flashback session then these are handled
# by gnome-flashback. Otherwise we have to handle them ourselves:
[ "$XDG_SESSION_DESKTOP" = 'herbstluftwm' ] && {
    hc keybind XF86MonBrightnessUp   spawn ~/.config/herbstluftwm/brightness.sh +
    hc keybind XF86MonBrightnessDown spawn ~/.config/herbstluftwm/brightness.sh -
    hc keybind XF86AudioRaiseVolume  chain , spawn pactl set-sink-mute @DEFAULT_SINK@ 0 , spawn pactl set-sink-volume @DEFAULT_SINK@ +2%
    hc keybind XF86AudioLowerVolume  chain , spawn pactl set-sink-mute @DEFAULT_SINK@ 0 , spawn pactl set-sink-volume @DEFAULT_SINK@ -2%
    hc keybind XF86AudioMute         spawn pactl set-sink-mute @DEFAULT_SINK@ toggle
    # shellcheck disable=2016
    hc keybind Print                 spawn scrot '%F-%s.png' -e 'mv $f ~/Pictures/'

    # if we're not on gnome, then keychain is not ran automatically
    # so we use hc to export these environment variables
    env_vars=$(gnome-keyring-daemon --start --components=ssh,gpg,secrets,pkcs11)
    for var in $env_vars ; do
        hc setenv "$(echo "$var" | cut -d'=' -f1)" "$(echo "$var" | cut -d'=' -f2-)"
    done
}

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-Tab       cycle_all +1
hc keybind $Mod-Shift-Tab cycle_all -1
hc keybind $Mod-BackSpace cycle_monitor

# rules
hc unrule -F
hc rule focus=on
hc rule title='slouch' focus=on pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on # manage=off
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on pseudotile=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK|DESKTOP)' manage=off

# theme
~/.config/herbstluftwm/theme.sh
hc set snap_distance 10
hc set snap_gap 0
hc set raise_on_focus 1
hc set raise_on_click 1
hc set auto_detect_monitors 1
hc set focus_follows_mouse 0

# unlock, just to be sure
hc unlock
hc set tree_style '╾│ ├└╼─┐'
hc detect_monitors

# panel things
killall hydra # hydra_listener
pdetach hydra
# pdetach hydra_listener
for monitor in $(hc list_monitors | cut -d: -f1) ; do
    # start panel on each monitor
    ~/.config/herbstluftwm/panel.sh "$monitor" &
done

# if this is our first startup then ...
if hc silent new_attr bool my_not_first_autostart ; then
    [ "$XDG_SESSION_DESKTOP" != 'herbstluftwm' ] && pdetach gnome-flashback
    gnome-keyring-daemon -rd
    st -e gnome_hc_startup
    pdetach compton
    pdetach ibus-daemon
fi
